require "macinbox/actions/create_box_from_hdd"
require "macinbox/actions/create_box_from_vmdk"
require "macinbox/actions/create_hdd_from_vmdk"
require "macinbox/actions/create_image_from_installer"
require "macinbox/actions/create_vmdk_from_image"
require "macinbox/actions/install_box"
